name: archeva_todo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  device_preview: ^1.0.0

  provider: ^6.0.2

  fluttertoast: ^8.0.8

  flutter_screenutil: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/Avenir-Medium.ttf
 

