name: archeva_todo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Visual Elements
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  flutter_staggered_grid_view: ^0.6.0
  animate_do: ^2.1.0

  # State Management
  provider: ^6.0.2

  # Date Operations
  intl: ^0.17.0
  date_util: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  device_preview: ^1.0.0
  flutter_screenutil: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/Avenir-Medium.ttf

